### PR TITLE
Automate release

### PR DESCRIPTION
**Pull request by ppuetsch**
Hi @Louisvdw , 

with this PR you can automatically create a release. Simply create a tag v7.8.9 and push it to the repo - and then release v7.8.9 will be build (i.e. the venus-data.tar.gz file will be created) and a release in Github will automatically be created containing this tar.gz file.

please note: 
I removed buildfiles.lst in favor of exclusions - so new files will be automatically included. 
I removed the dos2unix-commands in favor of .gitattributes - so git will properly checkout the files with the correct line endings

I hope this is what you needed. If not, let me know!

### CODE REVIEW

**Comment by ppuetsch** [comment]
Hi @Louisvdw , 

please find in this PR a Github Action to automate the Release. 
Let me know if you like to have something changed or would like to discuss something.

Best regards, 
Philip

**Comment by baranator** [comment]
as you are working on the file permissions:

i think `/etc/dbus-serialbattery/service/run` and  `/etc/dbus-serialbattery/service/log/run` will need a `+x` too?

**Comment by Louisvdw** [comment]
Yes they should have +x as well

**Comment by ppuetsch** [comment]
done

**Comment by ppuetsch** [comment]
> Yes they should have +x as well

done

**Review by Louisvdw — APPROVED** [review]

**Pull request merged**
