### PR TITLE
Add support for HLPdata BMS4S

### PR DESCRIPTION
**Pull request by peterohman**
BMS4S is a command controlled device. To enable managing it while connected via hlpdatabms4s.py the serial terminal hlpdatabms4s_miniterm.py is added. In a rough manner it handles the interference with hlpdatabms4s.py. But managing sessions are expected to be short, so the solution is regarded as good enough.

### CODE REVIEW

**Comment by peterohman** [comment]
Fixed (I hope)

**Comment by peterohman** [comment]
When I try to rerun the workflow I get  "Error: Resource not accessible by integration". And since I have not written the workflow I do not understand what resource it is referring to. So please give me a clue on what to do.

**Comment by peterohman** [comment]
One step forward, now: 8 files would be reformatted, 11 files would be left unchanged, 1 file would fail to reformat. 

Error: Process completed with exit code 123.

**Comment by mr-manuel** [comment]
I fixed the two files. It's ok now. The other errors can be ignored, they are fixed in my PR.

**Comment by peterohman** [comment]
Was probably if not ret is 0 earlierSkickat från min Galaxy
-------- Originalmeddelande --------Från: Manuel ***@***.***> Datum: 2023-04-27  17:32  (GMT+01:00) Till: Louisvdw/dbus-serialbattery ***@***.***> Kopia: peterohman ***@***.***>, Author ***@***.***> Ämne: Re: [Louisvdw/dbus-serialbattery] Add support for HLPdata BMS4S (PR #505) 
One thing:
if not ret is False:
why not
if ret is True:
?

**Comment by mr-manuel** [comment]
Could you please provide me the data for the [comparison table](https://louisvdw.github.io/dbus-serialbattery/general/features#bms-feature-comparison)?

**Comment by peterohman** [comment]
This is as I understand it can be interpreted. See also attached screenshots.

 


Feature

 

 

 

 

 

 

 

HLPdataBMS4S


Voltage

 

 

 

 

 

 

 

Yes


Current

 

 

 

 

 

 

 

Yes


Power

 

 

 

 

 

 

 

Yes


State Of Charge

 

 

 

 

 

 

 

Yes


Battery temperature

 

 

 

 

 

 

 

Yes


Mosfet temperature

 

 

 

 

 

 

 

Not applicable, uses bi-stable relays


Consumed Ah

 

 

 

 

 

 

 

Yes


Time-to-go

 

 

 

 

 

 

 

Calc


Min/max cell voltages

 

 

 

 

 

 

 

Yes


Min/max temperature

 

 

 

 

 

 

 

Yes


Installed capacity

 

 

 

 

 

 

 

Yes


Available capacity

 

 

 

 

 

 

 

Yes


Cell details

 

 

 

 

 

 

 

Yes


Raise alarms from the BMS

 

 

 

 

 

 

 

Yes


History of charge cycles

 

 

 

 

 

 

 

No


Charge current control management (CCCM)

 

 

 

 

 

 

 

Yes


Set battery parameters (DVCC)

 

 

 

 

 

 

 

Yes

**Comment by mr-manuel** [comment]
Since we are improving this driver constantly, we will add a new value in future. Is there any value that can be read from the BMS that is unique and helps to identify a BMS, when multiple BMS are attached? Like serial number?

If yes, please write it as string to `self.unique_identifier`. See https://github.com/mr-manuel/venus-os_dbus-serialbattery/commit/89cfe0a805b210ce64139efcf67c5bf2d98c3c8f#diff-9d9b25b4a5dcc9b6f162c96264601c1986789dd796a6b170586076a746fabbc0R102-R103

**Comment by peterohman** [comment]
No, today it is different BT names, but this is not seen by the BMS, so today you have to use installed capacity to diffrentiate, e.g. 130 Ah and 131 Ah. Id might be added in the future.

Bdw, a list of translation between self.identifier and Victrons identifiers would help to more easily make better drivers.

**Comment by mr-manuel** [comment]
Ok. You don't have to add the feature by installed capacity. This will be added to the battery class, if the unique identifier is not available.

**Comment by peterohman** [comment]
It does not want any limitations applied from outside, it controls the sources directly. It is following the guidelines in “ISO/TS 23625, Small craft — Lithium-ion batteries” and “ABYC E-13”.

**Review by Louisvdw — APPROVED** [review]

**Review by mr-manuel — COMMENTED** [review]
Somehow your driver is preventing the BMS that is tested after your BMS from beeing recognized, but it works the second time all BMS were tried.

<details><summary>With your driver</summary>

```bash
2023-06-12 11:39:08.537982500 INFO:SerialBattery:Starting dbus-serialbattery
2023-06-12 11:39:08.538924500 INFO:SerialBattery:dbus-serialbattery v1.0.20230611dev
2023-06-12 11:39:08.539367500 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
2023-06-12 11:39:08.539796500 INFO:SerialBattery:Testing Daly at address "\x40"
2023-06-12 11:39:08.683765500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:08.684352500 INFO:SerialBattery:Testing Daly at address "\x80"
2023-06-12 11:39:08.824932500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:08.825681500 INFO:SerialBattery:Testing Ecs
2023-06-12 11:39:08.904741500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:08.905370500 INFO:SerialBattery:Testing HeltecModbus
2023-06-12 11:39:12.715049500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:12.716151500 INFO:SerialBattery:Testing HLPdataBMS4S
2023-06-12 11:39:17.241819500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:17.242373500 INFO:SerialBattery:Testing Jkbms
2023-06-12 11:39:17.523428500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:17.526613500 INFO:SerialBattery:Testing Lifepower
2023-06-12 11:39:17.811083500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:17.814712500 INFO:SerialBattery:Testing LltJbd
2023-06-12 11:39:18.095208500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:18.098686500 INFO:SerialBattery:Testing Renogy at address "\x30"
2023-06-12 11:39:18.386284500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:18.389648500 INFO:SerialBattery:Testing Renogy at address "\xf7"
2023-06-12 11:39:18.668034500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:18.671680500 INFO:SerialBattery:Testing Seplos
2023-06-12 11:39:19.695775500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:19.696289500 INFO:SerialBattery:Testing ANT
2023-06-12 11:39:19.985956500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:19.989579500 ERROR:SerialBattery:>>> ERROR: Incorrect Data
2023-06-12 11:39:19.990051500 INFO:SerialBattery:Testing Sinowealth
2023-06-12 11:39:20.272670500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:20.779821500 INFO:SerialBattery:-- Testing BMS: 2 of 3 rounds
2023-06-12 11:39:20.779834500 INFO:SerialBattery:Testing Daly at address "\x40"
2023-06-12 11:39:20.920201500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:20.920850500 INFO:SerialBattery:Testing Daly at address "\x80"
2023-06-12 11:39:21.061789500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:21.062332500 INFO:SerialBattery:Testing Ecs
2023-06-12 11:39:21.488360500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:21.488884500 INFO:SerialBattery:Testing HeltecModbus
2023-06-12 11:39:25.311045500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:25.311557500 INFO:SerialBattery:Testing HLPdataBMS4S
2023-06-12 11:39:29.838805500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:39:29.839388500 INFO:SerialBattery:Testing Jkbms
2023-06-12 11:39:29.979059500 INFO:SerialBattery:Connection established to Jkbms
2023-06-12 11:39:29.979579500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB0
2023-06-12 11:39:29.979980500 INFO:SerialBattery:========== Settings ==========
2023-06-12 11:39:29.980431500 INFO:SerialBattery:> Connection voltage: 63.95V | Current: -0.0A | SoC: 94%
2023-06-12 11:39:29.980804500 INFO:SerialBattery:> Cell count: 18 | Cells populated: 0
2023-06-12 11:39:29.981186500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2023-06-12 11:39:29.981580500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 80.0A | MAX BATTERY DISCHARGE CURRENT: 120.0A
2023-06-12 11:39:29.981945500 INFO:SerialBattery:> CVCM:     True
2023-06-12 11:39:29.982320500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.65V
2023-06-12 11:39:29.982687500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2023-06-12 11:39:29.983054500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2023-06-12 11:39:29.983416500 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: False
2023-06-12 11:39:29.983771500 INFO:SerialBattery:Serial Number/Unique Identifier: Battery1_JK-B2A24S15P
2023-06-12 11:39:30.032444500 INFO:SerialBattery:DeviceInstance = 1
2023-06-12 11:39:30.033034500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB0
2023-06-12 11:39:30.057118500 INFO:SerialBattery:publish config values = 1
```

</details>

<details><summary>Without your driver</summary>

```bash
2023-06-12 11:36:29.637534500 INFO:SerialBattery:Starting dbus-serialbattery
2023-06-12 11:36:29.638513500 INFO:SerialBattery:dbus-serialbattery v1.0.20230611dev
2023-06-12 11:36:29.638978500 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
2023-06-12 11:36:29.639398500 INFO:SerialBattery:Testing Daly at address "\x40"
2023-06-12 11:36:29.783860500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:36:29.784490500 INFO:SerialBattery:Testing Daly at address "\x80"
2023-06-12 11:36:29.924793500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:36:29.925420500 INFO:SerialBattery:Testing Ecs
2023-06-12 11:36:30.003559500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:36:30.004095500 INFO:SerialBattery:Testing HeltecModbus
2023-06-12 11:36:33.811255500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-06-12 11:36:33.812354500 INFO:SerialBattery:Testing Jkbms
2023-06-12 11:36:33.879719500 INFO:SerialBattery:Connection established to Jkbms
2023-06-12 11:36:33.880345500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB0
2023-06-12 11:36:33.880815500 INFO:SerialBattery:========== Settings ==========
2023-06-12 11:36:33.881390500 INFO:SerialBattery:> Connection voltage: 64.05V | Current: -0.0A | SoC: 94%
2023-06-12 11:36:33.881932500 INFO:SerialBattery:> Cell count: 18 | Cells populated: 0
2023-06-12 11:36:33.882503500 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
2023-06-12 11:36:33.883019500 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 80.0A | MAX BATTERY DISCHARGE CURRENT: 120.0A
2023-06-12 11:36:33.883456500 INFO:SerialBattery:> CVCM:     True
2023-06-12 11:36:33.883916500 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.65V
2023-06-12 11:36:33.884350500 INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
2023-06-12 11:36:33.884780500 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
2023-06-12 11:36:33.885268500 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: False
2023-06-12 11:36:33.885744500 INFO:SerialBattery:Serial Number/Unique Identifier: Battery1_JK-B2A24S15P
2023-06-12 11:36:33.936144500 INFO:SerialBattery:DeviceInstance = 1
2023-06-12 11:36:33.936704500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB0
2023-06-12 11:36:33.960843500 INFO:SerialBattery:publish config values = 1
```

</details>

Could you check that please? Else we have to disable the driver by default.

**Comment by mr-manuel** [comment]
> I’ve noticed that the driver before hlpdatabms4s leaves data in the hlpdatabms4s inputbuffer since it does not read it until a linefeed is received, which makes it’s initial test fail every time. This problem must be the same for all drivers.

That is a good find. I will dig a bit deeper and see how I can solve this for all. Then I will remove it again from your driver, if that's the case.

@transistorgit maybe you have an idea on how to do that?

**Comment by transistorgit** [comment]
2 points:

### A
I don't think "old data" from the last driver is an issue, because the utils.read_serialport_data() does always 
```
        ser.flushOutput()
        ser.flushInput()
```
as first action. So the buffer is clean. There is one chance for this to be a problem nevertheless: there can by still comming new data in, or an always-sending device is connected (like a german gridmeter)

This leads to point 
### B
I already complained about the serial parser. It lacks some significant basic parsing elements, like checking the frame (header/startbyte, tail/checksum, significant other bytes that are specific to the expected answer. This is due to the aim to have a very universal receive routine, but this makes it very vulnerable. If there are excessive bytes before the telegram or there are bit errors (which come on any serial transmission statistically) this parser will just gulp what comes in. In this particular case, the drivers parse the wrong byte as packet length. 
I changed daly.py to use a local implementation to fix that. I think it makes no sense to try to improve the "universal" approach, the protocols are too different. Each driver should have it's local optimised parser.

I just saw that @peterohman also wrote his own parser, what is a good thing. Of course it should not wait for 1000 bytes, though. And the string "BMS4S" as a header marker could be found somewhere at the end of the string which will let crash the later index based parser. The buffer length is not checked.

**Comment by peterohman** [comment]
Old data is a problem. Flush only clears the drivers buffers, not the BMS input buffer.../Peter Skickat från min Galaxy
-------- Originalmeddelande --------Från: Bernd ***@***.***> Datum: 2023-06-12  22:09  (GMT+01:00) Till: Louisvdw/dbus-serialbattery ***@***.***> Kopia: peterohman ***@***.***>, Mention ***@***.***> Ämne: Re: [Louisvdw/dbus-serialbattery] Add support for HLPdata BMS4S (PR #505) 
2 points:
A
I don't think "old data" from the last driver is an issue, because the utils.read_serialport_data() does always
        ser.flushOutput()
        ser.flushInput()

as first action. So the buffer is clean. There is one chance for this to be a problem nevertheless: there can by still comming new data in, or an always-sending device is connected (like a german gridmeter)
This leads to point
B
I already complained about the serial parser. It lacks some significant basic parsing elements, like checking the frame (header/startbyte, tail/checksum, significant other bytes that are specific to the expected answer. This is due to the aim to have a very universal receive routine, but this makes it very vulnerable. If there are excessive bytes before the telegram or there are bit errors (which come on any serial transmission statistically) this parser will just gulp what comes in. In this particular case, the drivers parse the wrong byte as packet length.
I changed daly.py to use a local implementation to fix that. I think it makes no sense to try to improve the "universal" approach, the protocols are too different. Each driver should have it's local optimised parser.
I just saw that @peterohman also wrote his own parser, what is a good thing. Of course it should not wait for 1000 bytes, though. And the string "BMS4S" as a header marker could be found somewhere at the end of the string which will let crash the later index based parser. The buffer length is not checked.

**Pull request merged**
