### PR TITLE
read installed capacity at startup

### PR DESCRIPTION
**Pull request by transistorgit**
as it says

### CODE REVIEW

**Comment by mr-manuel** [comment]
Please check for black lint errors on the next PR :-) https://github.com/transistorgit/dbus-serialbattery/actions

I already fixed this one and will be merged later today.

**Comment by mr-manuel** [comment]
@transistorgit is this still needed?
https://github.com/Louisvdw/dbus-serialbattery/blob/8a37bf2802ffcb98baa8aa844e148d3da3718fcc/etc/dbus-serialbattery/config.default.ini#L221-L222

**Comment by transistorgit** [comment]
no I think not. (but i don't know if really all versions of daly bms can read out capacity though)

**Comment by mr-manuel** [comment]
Should be ok with this?

https://github.com/mr-manuel/venus-os_dbus-serialbattery/commit/e7943637e310089faf2666074eef24e206e39cc2

**Pull request merged**
