### PR TITLE
Add support for Seplos BMS

### PR DESCRIPTION
**Pull request by wollew**
I was unhappy with the limited data provided from the Seplos BMS via CAN bus so I decided to go the serial way. So far this works well for me, the alarm stuff is still mostly untested because changing the settings in the BMS app to trigger the corresponding alarm is a PITA. 
Feel free to comment on and/or fix my most likely rather unidiomatic Python usage, it is not my "native" language. 

(also see #138).

### CODE REVIEW

**Review by mr-manuel — COMMENTED** [review]
LGTM

**Comment by wollew** [comment]
You're quick. Thanks for the planned merge to `jkbms_ble `, I doesn't look like Louisvdw will be working on it too soon, so jkbms_ble looks like the new master to me :-) Seplos does have a bluetooth interface as well, no documentation though. Maybe I'll try to play around with it eventually.

**Comment by mr-manuel** [comment]
You're welcome. Louisvdw returns mid May :-)

**Comment by mr-manuel** [comment]
Could you please provide me the data for the [comparison table](https://louisvdw.github.io/dbus-serialbattery/general/features#bms-feature-comparison)?

**Comment by wollew** [comment]
I added the supported data in #591

**Comment by mr-manuel** [comment]
Since we are improving this driver constantly, we will add a new value in future. Is there any value that can be read from the BMS that is unique and helps to identify a BMS, when multiple BMS are attached? Like serial number?

If yes, please write it as string to `self.unique_identifier`. See https://github.com/mr-manuel/venus-os_dbus-serialbattery/commit/89cfe0a805b210ce64139efcf67c5bf2d98c3c8f#diff-9d9b25b4a5dcc9b6f162c96264601c1986789dd796a6b170586076a746fabbc0R102-R103

**Comment by wollew** [comment]
I don't think there is such a thing for the Seplos, neither the documentation nor the official app show any hints of something that could be used as a unique id.

**Comment by mr-manuel** [comment]
Ok, no problem.

**Comment by mr-manuel** [comment]
Do your BMS provide charge and discharge limits? https://github.com/Louisvdw/dbus-serialbattery/issues/4

If yes, could you change that the limits are read from the BMS?

**Review by Louisvdw — APPROVED** [review]

**Comment by mr-manuel** [comment]
Hello @wollew,

unfortunately some grid meters are now recognized as Seplos BMS. Please check in the `test_connection()` for a setting that is Seplos BMS specific, such as a field that contains Seplos or something like that.

**Comment by wollew** [comment]
Ok, that's going to prove interesting, because all the _documented_ commands to the BMS have no indication on what type of BMS it is in their response. There are more *un*documented commands that maybe could prove useful for this, I'll see what I can do, will most likely need a few days until I can work on it, though. 
Talking about BMS protocol documentation, I couldn't find a dedicated location to add them to the repo, would that be something to do?

**Comment by mr-manuel** [comment]
You can add the documentation to this PR in a comment. If someone searches for the integration it's found very fast. Ok, if there is no specific field or command maybe I have a solution

**Comment by wollew** [comment]
I've opened https://github.com/Louisvdw/dbus-serialbattery/pull/706 to maybe fix the grid meter problem, depends on what these meters return. It's obviously not the "right" fix, but until I've checked the other BMS commands it might just be good enough. Do you have a link to the grid meter issue?

**Comment by wollew** [comment]
Seplos BMS protocol spec: [16647-SEPLOS-BMS-Communication-ProtocolV2-0.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/11719026/16647-SEPLOS-BMS-Communication-ProtocolV2-0.pdf)

**Comment by mr-manuel** [comment]
There is no issue opened, but @transistorgit will send me the relevant data as soon he has time to reproduce the issue. You can see this as done, since I implemented a check to validate the received data for all BMS.

**Comment by andreas-bulling** [comment]
Would be fantastic to get Bluetooth support - is anyone working on this atm? No idea where to start, though - I assume there is no documentation?

**Comment by wollew** [comment]
I am not working on it. I did play around quite a while ago, but without any documentation (you're right, AFAIK there's none) did not get very far :-( Seeing that the "new" Seplos 3.0 has a new bluetooth app means they'll likely have a new protocol as well. So I am also doubtful it's worth investing too much time in supporting a version that's not even sold any more. But, if anyone comes up with reasonable docs I'm willing to try anyway.

**Pull request merged**
