### PR TITLE
Improve Maintainability

### PR DESCRIPTION
**Pull request by ppuetsch**
This PR
* consistently applies the same indentation (4 spaces) to all python files
* applies black code formatting to all python files
* checks for black code style violations in Github Actions
* Bumps Workflows in Github Actions to get rid of Warnings
* Cleans up the Workflows Yaml File
* Resolves flake8 style issues in utils and jkbms python files
* Introduced checks for flake8 or black findings in GH Actions

### CODE REVIEW

**Comment by ppuetsch** [comment]
Hi @Louisvdw , 
Thank you for your great project - I like it a lot. 
Please find in this PR some improvements concerning Code Formatting and the Usage of the CI. What do you think about it? If you like it, I will proceed on this path (e.g. add automated tests, get rid of CodeQL Warnings (and therewith re-enabling it) and so on.)

I am eager to receive your thoughts!

Best regards, 
Philip

**Comment by Louisvdw** [comment]
Hi @ppuetsch 
Thanks for the contribution. Hopefully I'll have some time to properly review it tonight.

It would be great to get some assistance with automations and fixing warnings. 
I also planned on creating a build action for automatic releases, so if you want to have a look at that as well it would be a great help. (create_build.sh must be called in a linux enviroment like Ubuntu)

**Comment by ppuetsch** [comment]
Hi @Louisvdw, 

yes - I will be more than happy to assist with that. 
Maybe we can create Issues so that we can align what to do / how to do. Or just leave me an E-Mail. :-)

Best regards, 
Philip

**Comment by Louisvdw** [comment]
I prefer issues. It's just easier to manage.

**Review by Louisvdw — APPROVED** [review]

**Pull request merged**
