### PR TITLE
TimeToGo 

### PR DESCRIPTION
**Pull request by corneel27**
Second PR (with corrections off typo's)now publishing to "TimeToGo"

### CODE REVIEW

**Review by Louisvdw — APPROVED** [review]

**Comment by Louisvdw** [comment]
fix #406

**Comment by mr-manuel** [comment]
Hi @corneel27,

do you have a screenshot how it looks in your Venus OS? I tried a few options and on my end it works only when I set `TIME_TO_SOC_VALUE_TYPE = 1`.

grafik

With all other options I get:

grafik

### dbus-spy

```
# TIME_TO_SOC_VALUE_TYPE = 1 --> working in Venus OS GUI
TimeToGo                                    90513
TimeToSoC/0                                115311
TimeToSoC/10                               102912
TimeToSoC/100                                   -
TimeToSoC/15                                96712
TimeToSoC/30                                78114
TimeToSoC/5                                109111
TimeToSoC/60                                40916
TimeToSoC/90                                 3719
TimeToSoC/95                                    -

# TIME_TO_SOC_VALUE_TYPE = 2 --> NOT working in Venus OS GUI
TimeToGo                           1 day, 6:51:36
TimeToSoC/0                       1 day, 15:18:53
TimeToSoC/10                      1 day, 11:05:14
TimeToSoC/100                                   -
TimeToSoC/15                       1 day, 8:58:25
TimeToSoC/30                       1 day, 2:37:57
TimeToSoC/5                       1 day, 13:12:04
TimeToSoC/60                             13:57:01
TimeToSoC/90                              1:16:05
TimeToSoC/95                                    -

# TIME_TO_SOC_VALUE_TYPE = 3 --> NOT working in Venus OS GUI
TimeToGo                         73421 [20:23:41]
TimeToSoC/0                93537 [1 day, 1:58:57]
TimeToSoC/10                     83479 [23:11:19]
TimeToSoC/100                                   -
TimeToSoC/15                     78450 [21:47:30]
TimeToSoC/30                     63364 [17:36:04]
TimeToSoC/5                88508 [1 day, 0:35:08]
TimeToSoC/60                      33190 [9:13:10]
TimeToSoC/90                       3017 [0:50:17]
TimeToSoC/95                                    -
```

For what were the `TimeToSo*` values planned, if they are not displayed anywhere? For fetching over MQTT or did you intend to add it to the GUI?

**Comment by corneel27** [comment]
I only fixed the generation of  correct "Time to go". 
I have nothing to do with publishing the correct values in the remote console or the vrm app/site.
I think Louis can answer your question.
I have installed the latest stable version on my Venus device, so I can't tell you anything of my experience with the develop version.

**Comment by mr-manuel** [comment]
> For what were the `TimeToSo*` values planned, if they are not displayed anywhere? For fetching over MQTT or did you intend to add it to the GUI?

@CaptKrisp or @Louisvdw maybe one of you can answer me that?

**Comment by CaptKrisp** [comment]
The TimeToSoC/* values are provided for programmatic convenience.  Most commonly used in NodeRed dashboards for display or flows for determining when to switch external loads/systems on/off, etc.
The use of these values in the VenusOS GUI doesn't seem practical since people generally are concerned only how much time remains before battery reaches a lower level of depletion or until fully charged.

**Comment by mr-manuel** [comment]
Thank you!

**Pull request merged**
