### PR TITLE
JKBMS Bluetooth - added battery details

### PR DESCRIPTION
**Pull request by mr-manuel**
- added: capacity
- added: MOS temperature
- added: charging switch status
- added: discharging switch status
- added: balancing switch status
- added: show if balancing is active and which cells are balancing
- added: cell imbalance alert

### CODE REVIEW

**Comment by baranator** [comment]
One suggestion: From the jkbms you can read `["settings"]["balance_trigger_voltage"]` maybe use this value (and a multiple of this value) rather than fixed values like 0.05 and 0.1 ?

**Comment by mr-manuel** [comment]
That‘s a good idea. I‘m currently still gaining experience at which point the cell voltage difference is critical. What would you say when the cell difference should be warning and critical?

**Comment by baranator** [comment]
> That‘s a good idea. I‘m currently still gaining experience at which point the cell voltage difference is critical. What would you say when the cell difference should be warning and critical?

Same here. No idea.

Critical-value however could be the one the bms has set as its trigger `["settings"]["balance_trigger_voltage"]` . And warning? maybe half that value?

**Comment by mr-manuel** [comment]
Regarding the cell voltage difference I found now that 5% of the maximum cell voltage or 200 mV are considered as critical.
So I would use 200 mA or 5% of OVP as critical and 120 mA or 3% of OVP as warning. Over Voltage Protection is fetched from the BMS.

**Pull request merged**
