### PR TITLE
Make things configurable

### PR DESCRIPTION
**Pull request by ppuetsch**
Now the configuration is back in - see 
https://github.com/Louisvdw/dbus-serialbattery/pull/389
https://github.com/Louisvdw/dbus-serialbattery/pull/386
for previous discussions on that topic. 

additionally, I made the bms_type configurable. If not set, behaviour is as before. But if configured, only the configured BMS will be tested. This will improve time-to-detection of the BMS after reoboot or deployment quite a bit.

I would suggest to update the documentation, in special the wiki, to reflect the changes here. A user is supposed to create a config.ini with his changes - maybe based on default_config.ini - but should NOT modify utils.py

### CODE REVIEW

**Review by Louisvdw — APPROVED** [review]
Thank you. This will work great. I'll update the wiki docs as well.

**Comment by mr-manuel** [comment]
@ppuetsch would it be better, if the `default_config.ini` is named `config.default.ini` so that in file explorer the default config and config files are nearby? Also if someone searches for config it's easier to find. What do you think?

**Comment by ppuetsch** [comment]
> @ppuetsch would it be better, if the `default_config.ini` is named `config.default.ini` so that in file explorer the default config and config files are nearby? Also if someone searches for config it's easier to find. What do you think?

Sound good!

**Comment by mr-manuel** [comment]
May you know, why the driver do not initialize when I set `BMS_TYPE = Jkbms`?

```
2023-02-17 08:58:43.472700500 INFO:SerialBattery:dbus-serialbattery v0.14.3
2023-02-17 08:58:44.975604500 ERROR:SerialBattery:ERROR >>> No battery connection at /dev/ttyUSB0
2023-02-17 08:58:45.128169500 + test -e /dev/ttyUSB0
2023-02-17 08:58:45.128923500 + cleanup
2023-02-17 08:58:45.129066500 + unlock_tty ttyUSB0
2023-02-17 08:58:45.129157500 + rm -f /var/lock/serial-starter/ttyUSB0
2023-02-17 08:58:59.983740500 + . /opt/victronenergy/serial-starter/run-service.sh
2023-02-17 08:58:59.983926500 ++ tty=ttyUSB0
2023-02-17 08:58:59.984046500 ++ product=
2023-02-17 08:58:59.984118500 ++ shift 2
2023-02-17 08:58:59.984228500 ++ . /opt/victronenergy/serial-starter/functions.sh
2023-02-17 08:58:59.984399500 +++ LOCK_DIR=/var/lock/serial-starter
2023-02-17 08:58:59.984720500 +++ mkdir -p /var/lock/serial-starter
2023-02-17 08:58:59.989873500 ++ trap term INT TERM
2023-02-17 08:58:59.989993500 ++ trap cleanup EXIT
2023-02-17 08:58:59.990263500 + app='python /opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py'
2023-02-17 08:58:59.990359500 + args=/dev/ttyUSB0
2023-02-17 08:58:59.990449500 + start /dev/ttyUSB0
2023-02-17 08:58:59.990651500 + log 'Starting dbus-serialbattery.py on ttyUSB0'
2023-02-17 08:58:59.990729500 + test -t 1
2023-02-17 08:58:59.991626500 + pid=3095
2023-02-17 08:58:59.991775500 + wait 3095
2023-02-17 08:58:59.992072500 + python /opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py /dev/ttyUSB0
```

If I leave it empty it works.

```
2023-02-17 08:54:54.757591500 INFO:SerialBattery:Starting dbus-serialbattery
2023-02-17 08:54:54.759697500 INFO:SerialBattery:dbus-serialbattery v0.14.3
2023-02-17 08:54:54.760534500 INFO:SerialBattery:Testing LltJbd
2023-02-17 08:54:55.046253500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-02-17 08:54:55.049814500 INFO:SerialBattery:Testing Ant
2023-02-17 08:54:55.334325500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-02-17 08:54:55.340885500 ERROR:SerialBattery:>>> ERROR: Incorrect Data
2023-02-17 08:54:55.342190500 INFO:SerialBattery:Testing Daly
2023-02-17 08:54:55.622746500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-02-17 08:54:55.626244500 INFO:SerialBattery:Testing Daly
2023-02-17 08:54:55.932596500 ERROR:SerialBattery:>>> ERROR: No reply - returning
2023-02-17 08:54:55.936108500 INFO:SerialBattery:Testing Jkbms
2023-02-17 08:54:56.074090500 INFO:SerialBattery:Connection established to Jkbms
2023-02-17 08:54:56.074716500 INFO:SerialBattery:Battery Jkbms connected to dbus from /dev/ttyUSB0
2023-02-17 08:54:56.075213500 INFO:SerialBattery:=== Settings ===
2023-02-17 08:54:56.075786500 INFO:SerialBattery:> Connection voltage 53.53V | current 5.88A | SOC 61%
2023-02-17 08:54:56.076288500 INFO:SerialBattery:> Cell count 16 | cells populated 0
2023-02-17 08:54:56.076782500 INFO:SerialBattery:> CCCM SOC True | DCCM SOC True
2023-02-17 08:54:56.077291500 INFO:SerialBattery:> CCCM CV True | DCCM CV True
2023-02-17 08:54:56.077810500 INFO:SerialBattery:> CCCM T False | DCCM T False
2023-02-17 08:54:56.078308500 INFO:SerialBattery:> MIN_CELL_VOLTAGE 2.9V | MAX_CELL_VOLTAGE 3.45V
2023-02-17 08:54:56.143501500 INFO:SerialBattery:DeviceInstance = 1
2023-02-17 08:54:56.144298500 INFO:SerialBattery:com.victronenergy.battery.ttyUSB0
2023-02-17 08:54:56.163760500 INFO:SerialBattery:publish config values = 1
```

**Pull request merged**
