### PR TITLE
Renogy

### PR DESCRIPTION
**Pull request by Louisvdw**

### CODE REVIEW

**Comment by Louisvdw** [comment]
Hi @gambleben 
If possible can you test https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.12b4 to see if that still works with your version of the Renogy.

**Comment by gambleben** [comment]
Hi Louis,

I'll take a look and try to test soon.  I finally got to install my
batteries in a new travel trailer with the Cerbo a couple months ago.  I
have 3 batteries so I created a fork and made a handful of changes to fix
bad readings, work correctly with Python 3, and handle my multiple
batteries (by making them look like a single battery with 12 cells).  I
also had to lengthen the polling interval as 1 second wasn't quite enough
time to refresh all 3 batteries for all of the values, at least in the way
that I'm pulling them right now.  I suspect the reason the addresses for
the batteries are different is that I also use the Renogy bluetooth monitor
and I've found that it goes through a process to discover any attached
batteries and assign them new modbus addresses when it is first plugged in.

I also found full, correct documentation for all of the addresses, so I
planned on adding in the relevant alarms when I get time.

I'd like to get your input on the best way to handle multiple Renogy
batteries.  I think we would want to have a routine that scans the
potential address range when the driver is initialized, adds a new battery
for each address that responds, and then the driver would loop through and
poll them as normal.  What I'm not sure of is how to add the new batteries
individually.

**Comment by gambleben** [comment]
Are you including minimalmodbus with the project now?  That would honestly make implementation of the full Renogy spec much easier.

**Comment by Louisvdw** [comment]
After v0.11 the driver needed some changes to be able to work with the structure changes in VenusOS 2.80+ and also for python3. These are not backward compatable anymore which ment we can assume everything will be in Python3 and thus I could include Minimalmodbus. 
So you can assume it will be available, and use it.

**Comment by Louisvdw** [comment]
I have been playing with the multiple battery (VenusOS cal them Multi Banks) feature a bit. 

Here is how I see the multi battery working. 
The serialbattery will create it's own custom path in the dbus.
Each battery/BMS will read it's data and "store" that under this custom dbus path.
There has to be a master service that will be doing the publish to the dbus. It will combine all the data from the custom dbus path for each bms and then publish this to the victron paths. 

There are also a few new batteries that I am working on that also need similar changes and it could also help with easier setup up for users. What happens with the SBMS is that the battery is not polled for data, but it just publish it so you need to be listening. And so it needs some master service as well.

The master service could also be what is installed by default. And then the user can do a battery detection so that the driver does not need to run though all the possible battery types each time. They can then also setup that battery with the settings needed which will move all the settings out from utils.py, but this needs a GUI 

There is also a ticket open to[ add bluetooth support](https://github.com/Louisvdw/dbus-serialbattery/issues/13) for the driver. One of the reasons I have started with that is the set up that is needed to be detected (addresses) and I think the driver needs a UI that can handle that. Seeing as you have done a bit of the bluetooth already maybe we can start with that using any hard codes for now and then move to a GUI and other BMS step by step?

**Pull request merged**
