### PR TITLE
Support for Daly CAN Bus

### PR DESCRIPTION
**Pull request by SamuelBrucksch**
~~This is still highly experimental.~~

Install python-can on Venus OS:
As pip3 is not available this needs to be done manually, you can check the download link here: https://pypi.org/project/python-can/#files
```
wget https://files.pythonhosted.org/packages/1f/f7/a643cba269d59e108fe4c1854a8e71d5cdadadd4de1b9c8862b190171122/python-can-4.0.0.tar.gz
tar xf python-can-4.0.0.tar.gz
cd python-can-4.0.0
python3 setup.py develop
```

In `dbus-serialbattery.py` comment all battery types, and uncomment DalyCAN, so it is the only BMS that is tried to connect to.

In Venus OS settings via Remote Console go to `Settings`->`Services`->`VE.Canport`->`CAN-bus profile` and ~~click disabled. Then on console via SSH enter `ip link set can0 up type can bitrate 250000`~~ check that a profile with 250k is selected.

As we do not need a serial port, this can be executed from command line directly, without searching for a serial device.

```
cd /data/etc/dbus-serialbattery
python3 dbus-serialbattery
```

If everything works well and cables were made correctly, you should see data on remote console.

To test that everything works you can also use Venus OS CLI tools:
```
candump can0
```
This will list all the communication on can0

```
cansend can0 18950140#
```
This will request the battery cell voltages. Response will look like this:
```
  candump can0
  cansend can0 18950140# [execute this on a second terminal]
  can0  18950140   [0] 
  can0  18954001   [8]  01 0D 7D 0D 7E 0D 7E 58
  can0  18954001   [8]  02 0D 7E 0D 7F 0D 7E 58
  can0  18954001   [8]  03 0D 7E 0D 7F 0D 7E 58
  can0  18954001   [8]  04 0D 7E 0D 7E 0D 7E 58
  can0  18954001   [8]  05 0D 7E 0D 7F 0D 7F 58
  can0  18954001   [8]  06 0D 7F 0D 7F 0D 7F 58
```

### CODE REVIEW

**Comment by SamuelBrucksch** [comment]
@Louisvdw this sounds a bit complex but a few things can be made easier, like that you do not need to manually setup can0, if i add the right filters to the can bus library. However can does not need a serial, so we need to add a detection mechanism somewhere.

That detection mechanism could for example execute the cansend and candump command line tool and if we get data, we know we have a connected can interface. Is that something we could easily add to the detection mechanism? Because in that case we could also do the auto detection and add a small code snipped, to switch between CAN and serial based on the detection.

**Comment by Louisvdw** [comment]
Hi Samuel
Yes that has always been the issue as the CANbus is not running through the serial starter mechanism that the driver normally use. There are a few other batteries that I am working on that also work a bit different. I'll play around with a few options on how to detect the CAN as well.

**Comment by SamuelBrucksch** [comment]
I just added the can filters, so no need to manually set up can anymore as it is set to 250k by default, we can still mention to check if it is really set to 250k.

**Comment by danygi79** [comment]
Is it possible to configure the CAN bus at 500K? On multiplus II GX it is not possible to select the speed at 250k and therefore it does not work.

**Comment by SamuelBrucksch** [comment]
Daly has 250k.

**Comment by geromd** [comment]
> Is it possible to configure the CAN bus at 500K? On multiplus II GX it is not possible to select the speed at 250k and therefore it does not work.

You need to update the Multiplus II GX Firmware. Than you have the Menue to set the 250k  for CAN
CAN
N

**Comment by LukasBenner** [comment]
How did you connect the MP2 GX to the Daly BMS? Simply an adapter from daly bms port to rj45 of MP2 GX?

**Comment by SamuelBrucksch** [comment]
Daly has CAN bus so i just connected pins L and H from Daly to can port from Cerbo.

**Comment by stanhausc** [comment]
Hi, no need to change utils.py file?

I'm trying to implement can communication with a BMS Fox. [Fox BMS.](https://iisb-foxbms.iisb.fraunhofer.de/foxbms/gen1/docs/html/latest/getting_started/communicating/communicating.html)

image

**Comment by Mipamlius** [comment]
Hello Maybe a stupid question but does can bus work with venus os 2.9 on raspberry pi ?

**Comment by SamuelBrucksch** [comment]
Just tried venus os 2.92 on a Cerbo and it works. Not sure about the Raspi.

**Comment by Newti04** [comment]
Hello Samuel,
I will use it on a raspberry py 3b+ with a can-hat from waveshare.
I installed the python-can-4.0 package and it is possible to use the commands:
candump can0 and cansend can0 18950140# (in extra terminal)
It shows the Voltages from the battery-cells. (My can-hat uses can8 and can9 instead of can0)
Now I want to install dbus-seriallbattery, but I cannot find the right branch witch supports the can-connection. And the code in this pullrequest does not work with the actual released code 0.14.3
Please can you show me, where I can get it.
BR
Claus

**Comment by SamuelBrucksch** [comment]
I'm still on the code of this branch, as it works fine for me. There is no newer version of this.

**Comment by Newti04** [comment]
Hello Samuel,
I found the problem, I disconnect 2 DalyBMS, so with one DalyBMS connected it works :-)
So I have to check, what to do, to use 3 BMS at one can-bus.
Thanks for your help.
Claus

**Comment by stanhausc** [comment]
> Hello Samuel, i tried this branch [[36f297a](https://github.com/Louisvdw/dbus-serialbattery/commit/36f297ad284cdb7772a024eab97212417484bcb0)]: https://github.com/SamuelBrucksch/dbus-serialbattery/tree/samuel/add-daly-can-support I copied dbus-serialbattery-samuel-add-daly-can-support/etc/dbus-serialbattery to /data/etc/dbus-serialbattery Then i edit /data/etc/dbus-serialbattery/dbus-serialbattery.py from dbushelper import DbusHelper from utils import DRIVER_VERSION, DRIVER_SUBVERSION, logger import logging
> 
> # from lltjbd import LltJbd
> # from daly import Daly
> # from ant import Ant
> # from jkbms import Jkbms
> # from sinowealth import Sinowealth
> # from renogy import Renogy
> # from revov import Revov
> from daly_can import DalyCAN
> 
> # from mnb import MNB
> ... def get_battery_type(_port): # all the different batteries the driver support and need to test for battery_types = [ # LltJbd(port=_port, baud=9600), # Ant(port=_port, baud=19200), # Daly(port=_port, baud=9600, address=b"\x40"), # Daly(port=_port, baud=9600, address=b"\x80"), # Jkbms(port=_port, baud=115200), # Sinowealth(port=_port, baud=9600), # Renogy(port=_port, baud=9600), # Revov (port=_port, baud=9600), DalyCAN(port=_port, baud=9600), # MNB(port=_port, baud=9600), ] and I changed can0 to can 8 in /data/etc/dbus-serialbattery/daly_can.py ... {"can_id":self.response_cell_balance, "can_mask": 0xFFFFFFF}, {"can_id":self.response_alarm, "can_mask": 0xFFFFFFF}] self.bus = can.Bus(interface='socketcan', channel='can8', receive_own_messages=False, can_filters=can_filters) ... because my can-device is named can8 cansend can8 18950140# shows in an extra terminal candump can8 .... can8 307 [8] 12 34 56 78 56 49 43 00 can8 305 [8] 00 00 00 00 00 00 00 00 can8 307 [8] 12 34 56 78 56 49 43 00 can8 18950140 [0] can8 18954001 [8] 01 0D 1B 0D 1D 0D 1D 00 can8 18954001 [8] 01 0D 1B 0D 1D 0D 1D C0 can8 18954001 [8] 01 0D 19 0D 1B 0D 1C 88 can8 18954001 [8] 02 0D 1E 0D 1F 0D 1E 00 can8 18954001 [8] 02 0D 1D 0D 1D 0D 1D C0 can8 18954001 [8] 02 0D 1D 0D 1D 0D 1D 88 can8 18954001 [8] 03 0D 1F 0D 1E 0D 1F 00 can8 18954001 [8] 03 0D 1D 0D 1D 0D 1E C0 can8 18954001 [8] 03 0D 1D 0D 1D 0D 1B 88 can8 18954001 [8] 04 0D 1E 0D 1D 0D 1E 00 can8 18954001 [8] 04 0D 1D 0D 1E 0D 1D C0 can8 18954001 [8] 04 0D 1A 0D 1B 0D 1B 88 can8 18954001 [8] 05 0D 1E 0D 1E 0D 1E 00 can8 18954001 [8] 05 0D 19 0D 1D 0D 1D 88 can8 18954001 [8] 06 0D 1B 0D 1E 0D 1E 00 can8 18954001 [8] 05 0D 1D 0D 1D 0D 1D C0 can8 18954001 [8] 06 0D 18 0D 1D 0D 1D 88 can8 18954001 [8] 06 0D 1B 0D 1D 0D 1D C0 can8 305 [8] 00 00 00 00 00 00 00 00 can8 307 [8] 12 34 56 78 56 49 43 00 can8 305 [8] 00 00 00 00 00 00 00 00 .... It shows the cell-numbers 3 times, because I have 3 DalyBMS 16S connected to the can-bus.
> 
> When I start dbus-serialbattery with:: python3 /data/etc/dbus-serialbattery/dbus-serialbattery.py can8 I get this output: INFO:SerialBattery:Starting dbus-serialbattery INFO:SerialBattery:dbus-serialbattery v0.12b2 INFO:SerialBattery:Testing DalyCAN INFO:SerialBattery:DalyBMS 16 cells INFO:SerialBattery:Connection established to DalyCAN INFO:SerialBattery:Battery connected to dbus from can8 INFO:SerialBattery:=== Settings === INFO:SerialBattery:> Connection voltage NoneV | current NoneA | SOC None% INFO:SerialBattery:> Cell count 16 | cells populated 0 INFO:SerialBattery:> CCL Charge NoneA | DCL Discharge NoneA INFO:SerialBattery:> MIN_CELL_VOLTAGE 2.9V | MAX_CELL_VOLTAGE 3.45V INFO:SerialBattery:DeviceInstance = 2 INFO:SerialBattery:com.victronenergy.battery.can8 WARNING:SerialBattery:read_soc_data - triesValid 2 WARNING:SerialBattery:read_soc_data - triesValid 1 Traceback (most recent call last): File "/data/etc/dbus-serialbattery/dbushelper.py", line 176, in publish_battery self.publish_dbus() File "/data/etc/dbus-serialbattery/dbushelper.py", line 186, in publish_dbus self._dbusservice['/Soc'] = round(self.battery.soc, 2) TypeError: type NoneType doesn't define **round** method
> 
> Cell count 16 is correct, the other things are None
> 
> Do you have any hints for me? BR Claus

The error is in the frame you are receiving from the SOC, you receive 'NoneType', I believe it is not returning anything. Have a look at what you're getting, or you can try adding 'self.soc = 50' to your code, and see if it works, and then fix that error.

**Comment by Newti04** [comment]
Hello Samuel,
yes, I have set different IDs for each BMS with the PC-Software.
You wrote -> But querying multiple BMS with different IDs is also not supported.
You mean it is not supported by this Software-Release, but it could be possible with rewriting/changing it, if the BMSs have different IDs on one can-bus.
Ok, my can-hat has 2 can-bus connections and I could use the second can9 for the second BMS, but the intention was to use one connection for all 3 BMS.
I see, if I start it with different args, it gets different DeviceInstance numbers, so it is possible to use it with different ports.

Do you know, how to check, how the BMS marks the data with his BMS-ID? ore how to filter the data from each BMS?
BR
Claus

**Comment by Newti04** [comment]
In the script daly_can.py there is
    # command bytes [Priority=18][Command=94][BMS ID=01][Uplink ID=40]
    command_base = 0x18940140
    command_soc = 0x18900140
so I tried cansend 
cansend 18950140#
cansend 18950240#
cansend 18950340#
cansend 18950440#
cansend 18950540#
... and so on, but only with result on: cansend 18950140#

I have to check tomorrow with the PC, if the IDs on the BMSs are correct set.

**Comment by transistorgit** [comment]
Hi guys,

What's the Status here? Any new insights about multiple bms on one port?

I initially wanted this also. My findings were: 
- You have to order a daly bms with can support explicitely
- You have to also mention that you want to use them in parallel
-  And you also have to buy the WNT Connection boards

On the wnt, you choose the address by dip switch. 

I got it running partly, but some read values were garbage. So I ditched it and use normal serial connection. But I'm still interested if there is a working solution.

**Comment by SirDingDong** [comment]
Hi, i am a bit lost, is there a step by step how to set up can connection? Serial is working, but also want to try can =)

**Comment by mr-manuel** [comment]
I will merge this PR and make some changes to work with the latest version. Since the Bluetooth driver is also not needing the serial adapter I make some changes to the install script so you can specify the can port number in the `config.ini`.

**Comment by mr-manuel** [comment]
Is there a simple way for a user to display all CAN devices like `can0`, `can8` and so on in case it's not the default one?

**Comment by mr-manuel** [comment]
Please try the latest `nightly` from the `dev` branch. To enable CAN add `CAN_PORT = can0` to the `config.ini`.

**Comment by SamuelBrucksch** [comment]
Hi @mr-manuel , sorry for the late reply, i just tried it and set the CAN_PORT to can0, however it does not seem to have any effect. this is the log:
```
root@einstein:/data/etc/dbus-serialbattery# python3 dbus-serialbattery.py 
INFO:SerialBattery:
INFO:SerialBattery:Starting dbus-serialbattery
INFO:SerialBattery:dbus-serialbattery v1.0.20231010dev2
INFO:SerialBattery:No Port needed
INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
INFO:SerialBattery:-- Testing BMS: 2 of 3 rounds
INFO:SerialBattery:-- Testing BMS: 3 of 3 rounds
ERROR:SerialBattery:ERROR >>> No battery connection at /dev/ttyUSB9
root@einstein:/data/etc/dbus-serialbattery# 
```

**Comment by mr-manuel** [comment]
Did you troubleshoot the CAN connection with can tools in the first post?

**Comment by SamuelBrucksch** [comment]
No, i just stopped my working daly can implementation, renamed it to *_old, installed the nightly from develop at the old location and setup everything and reinstalled locally, restarted and then i didnt see anything. so i tried to start it manually by setting can0 and daly programmatically, and it didn't work. As i have a working version, i didn't spend much time on debugging. So not sure, what exactly was wrong here. After i switched back to my old version, everything worked again, so it's probably nothing related to the hardware/can setup.

**Comment by mr-manuel** [comment]
Since I could not test the integrations it will be nice, if you can debug it.

**Pull request merged**
