### PR TITLE
Increase max supported battery capacity from 1000 to 2000 ampere-hour.

### PR DESCRIPTION
**Pull request by pitzer**
I have a 1500 Ah battery :-)

### CODE REVIEW

**Comment by mr-manuel** [comment]
What kind of battery is that? O_O

**Comment by pos-ei-don** [comment]
> What kind of battery is that? O_O

i have 1800 Ah aswell (52V lifepo4)

**Comment by mr-manuel** [comment]
I changed it in my repo, this makes a few things a bit easier. https://github.com/mr-manuel/venus-os_dbus-serialbattery/commit/0d35803a456df38a9c7019d0ca69b336c3af4e17

**Comment by pitzer** [comment]
Thank you so much @mr-manuel!

**Comment by mr-manuel** [comment]
You're welcome

**Pull request closed without merging**
